/* Generated by bin2c, do not edit manually */
#ifndef __RomC_VicChars_h_included
#define __RomC_VicChars_h_included

/* Contents of file characters.901460-03.bin */
#define VicChars901460_03_size 4096
extern const unsigned char VicChars901460_03[4096];

#endif    /* __RomC_VicChars_h_included */
